"""Add language column to Post

Revision ID: 51533208c4da
Revises: 
Create Date: 2025-08-12 14:37:51.803973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51533208c4da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('title_en', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('title_pt', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('content_en', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('content_pt', sa.Text(), nullable=True))

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('title_en', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('title_pt', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('content_en', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('content_pt', sa.Text(), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('author_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['author_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['author_id'], ['id'])
        batch_op.alter_column('author_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('content_pt')
        batch_op.drop_column('content_en')
        batch_op.drop_column('title_pt')
        batch_op.drop_column('title_en')
        batch_op.drop_column('language')

    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_column('content_pt')
        batch_op.drop_column('content_en')
        batch_op.drop_column('title_pt')
        batch_op.drop_column('title_en')
        batch_op.drop_column('language')

    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), nullable=False),
    sa.Column('password', sa.VARCHAR(length=200), nullable=False),
    sa.Column('role', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###
